#!/bin/bash
int counter=1;

for f in $(ls -1)
    do
        new_filename=$(printf "%04d" ${counter})
        echo "renaming ${f} ..to.. ${new_filename}"
        mv ${f} ${new_filename}
        (( counter=${counter}+1 ))
    done
