#!/bin/bash

counter=1;
for f in $(ls -1)
    do
        new_filename=$(printf "%04d" ${counter})
	if [ ${f} = "rename_hs" ]; then
		echo "${f} is bash file."
	else
	        echo "renaming ${f} ..to.. ${new_filename}"
	        mv ${f} ${new_filename}
		(( counter=${counter}+1 ))
	fi
	
    done

######################ReadME###############################
#							  #
# bash ./rename_hs 또는 ./rename_hs로 실행시킬 경우에       #
# 폴더 내에 있는 파일(rename_hs 제외)이 0001~9999로 재정렬됨 #
#							  #
###########################################################
